### ISSUE TITLE
improvements to Tracking

### ISSUE THREAD

**Issue by mixmixmix** [ctorney/uavTracker#16]
- [x] in/out fps and step size must be configurable explained and matched

**Comment by mixmixmix** [comment]
In trackign config define fps and step size, based on which output fps will be calculated. 
The file metadata might not be accurate (And often isn't) that is why it must be in config file:
Config:
```
#TRACKING and TESTING setup:
tracking_setup: "mk1"

mk1:
  videos_name_regex: "videos/*.mp4" #for use by transform.py which also preps the following yml file
  videos_fps: 30
  link_iou: 0.1
  step_frames: 5 #how many frames between each step of a tracker/downsampling. Remember to adjust link_iou if jump is bigger
videos_list: "horse_videos.yml" #after transforms.py was run this is where video list live
```


Logic in tracker:
```
#frame rate calculus:
step_frames = config[tracking_setup]['step_frames']
videos_fps = config[tracking_setup]['videos_fps']
output_vid_fps = round(videos_fps/step_frames)
```
